### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by 0x14Rp** [WhiteVermouth/XcodeTheme#1]
Hi bro!

My stacktrace: https://gist.github.com/RafaelPuerta/1b43c6b861e9677bc8e52b8093cb27ce

Operation system : windows 10 version 21H1
IDE :WebStorm 2021.2.2 Build #WS-212.5284.41
Xcode Theme 1.4.0

**Comment by WhiteVermouth** [comment]
Can't reproduce here and works well on macOS. Maybe a Windows specific bug? Have you tried a reinstall?
