### ISSUE TITLE
Color of comment is different from Xcode's

### ISSUE THREAD

**Issue by Xwoder** [WhiteVermouth/XcodeTheme#2]
The color of comment in this theme is gray, but it should be green.

**Comment by WhiteVermouth** [comment]
Thanks for your feedback. This is not a mistake. The **Classic Xcode Theme**'s comment color is green, while the current **Default Xcode Theme**'s comment color is gray.

<img width="942" alt="image" src="https://user-images.githubusercontent.com/13076049/181689703-07e70d52-92b2-4e6e-8401-2d3888dc1e61.png">

**Comment by Xwoder** [comment]
Thank you, got it. I haven't used Xcode for a long time.
