### ISSUE TITLE
v1.6.2 Dark theme is showing white in PyCharm for the code editing panel and remaining section is black

### ISSUE THREAD

**Issue by Tuhin-thinks** [WhiteVermouth/XcodeTheme#5]
`v1.6.2` Dark theme is showing white in PyCharm for the code editing panel and remaining section is black.

Note: This behavior is noticed in both windows and Linux OS.

**Please fix this issue, xcode is my most favorite theme plugin. I can't work without this in my office 😔**

![image](https://github.com/WhiteVermouth/XcodeTheme/assets/48290754/31095d23-674e-4f55-8e45-b89dd92e42da)

**Comment by WhiteVermouth** [comment]
To workaround the bug in the latest IDE, follow these steps:

1. Go to the "Settings" menu.
2. Navigate to "Editor" and select "Color Scheme".
3. On the right panel, choose "Xcode Light" or "Xcode Dark" as the color scheme.
4. Click "OK" to apply the changes.

This should resolve the issue with the color scheme in the IDE.

<img width="1012" alt="image" src="https://github.com/WhiteVermouth/XcodeTheme/assets/13076049/79e48c86-521a-494f-8057-af3ef68f707d">

**Comment by Tuhin-thinks** [comment]
Work around worked 👍🏻

**Comment by firescout** [comment]
Also happened in GoLand  2023.1.4
Work around did the trick

**Comment by WhiteVermouth** [comment]
Try v1.6.3

In version v1.6.3, a patch has been added. When you switch the theme to either "Xcode Light" or "Xcode Dark" from any other theme, the plugin will automatically adjust the editor color scheme to match the selected theme. The above workaround is no longer needed.

PS: If you encounter any problem after upgrading to v1.6.3, try restarting IDE firstly.

**Comment by Tuhin-thinks** [comment]
@WhiteVermouth Upgraded to v1.6.3 on linux environment. The bug seems to be resolved.
