### ISSUE TITLE
Kebab button in Run Widget toolbar is hardly visible in new UI

### ISSUE THREAD

**Issue by userlond** [WhiteVermouth/XcodeTheme#9]
Webstorm 2024.1
UI theme is Xcode Light

![scr_20240405_100609_447](https://github.com/WhiteVermouth/XcodeTheme/assets/7788670/022abb82-13cd-4b08-bf42-2c9e661b9fee)
![scr_20240405_100614_755](https://github.com/WhiteVermouth/XcodeTheme/assets/7788670/49ac0a12-18bf-44ce-9588-4c90d4e6e406)

**Comment by WhiteVermouth** [comment]
I've fixed the RunWidget icon color error in v1.7.0, which will be downloadable once JetBrains approved.
